sinlin:add.o main.o print.o del.o save.o mod.o search.o rev.o
	cc add.o main.o print.o del.o save.o mod.o search.o rev.o -o sinlin
main.o:main.c
	cc -c main.c -o main.o
print.o:print.c
	cc -c print.c -o print.o
add.o:add.c
	cc -c add.c -o add.o
del.o:del.c
	cc -c del.c -o del.o
save.o:save.c
	cc -c save.c -o save.o
mod.o:mod.c
	cc -c mod.c -o mod.o
search.o:search.c
	cc -c search.c -o search.o
rev.o:rev.c
	cc -c rev.c -o rev.o
