project :sort1.o updatelist.o save.o search.o modify.o add.o print.o delete.o main.o
	cc sort1.o updatelist.o save.o search.o modify.o add.o print.o delete.o main.o -o project
main.o  : main.c
	 cc -c main.c -o main.o
print.o : print.c
	 cc -c print.c -o print.o
delete.o: delete.c
	  cc -c delete.c -o delete.o
add.o   : add.c
	  cc -c add.c -o add.o
modify.o : modify.c
	  cc -c modify.c -o modify.o
search.o : search.c
	   cc -c search.c -o search.o
updatefile.o : updatefile.c
	    cc -c updatelist.c -o updatelist.o
save.o    :save.c
	    cc -c save.c -o save.o
sort1.o    :sort1.c
	    cc -c sort1.c -o sort1.o 	
