project : insert.o  delete.o print.o reverse.o  sort.o main.o
	cc insert.o delete.o print.o reverse.o sort.o main.o -o project
main.o : main.c
	cc -c main.c -o main.o
insert.o : insert.c
	cc -c insert.c -o insert.o
delete.o: delete.c 
	cc -c delete.c -o delete.o
print.o :print.c
	cc -c print.c -o print.o
revrse.o :reverse.c
	cc -c reverse.c -o revrse.o
sort.o : sort.c
	cc -c sort.c -o sort.o
