a.out:add.o main.o print.o del.o save.o update.o
	cc add.o print.o main.o del.o save.o update.o
main.o:main.c
	cc -c main.c -o main.o
add.o:add.c
	cc -c add.c -o add.o
print.o:print.c
	cc -c print.c -o print.o
del.o:del.c
	cc -c del.c -o del.o
save.o:save.c
	cc -c save.c -o save.o
update.o:
	cc -c update.c -o update.o

